# Generated by Django 3.0.4 on 2020-03-29 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(max_length=3, verbose_name='Strength')),
                ('intelligence', models.IntegerField(max_length=3, verbose_name='Intelligence')),
                ('education', models.IntegerField(max_length=3, verbose_name='Education')),
                ('dexterity', models.IntegerField(max_length=3, verbose_name='Dexterity')),
                ('accuracy', models.IntegerField(max_length=3, verbose_name='Accuracy')),
                ('agility', models.IntegerField(max_length=3, verbose_name='Agility')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
