# Generated by Django 3.0.4 on 2020-03-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20200329_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='accuracy',
            field=models.IntegerField(default=1, verbose_name='Accuracy'),
        ),
        migrations.AlterField(
            model_name='player',
            name='agility',
            field=models.IntegerField(default=1, verbose_name='Agility'),
        ),
        migrations.AlterField(
            model_name='player',
            name='dexterity',
            field=models.IntegerField(default=1, verbose_name='Dexterity'),
        ),
        migrations.AlterField(
            model_name='player',
            name='education',
            field=models.IntegerField(default=1, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='player',
            name='intelligence',
            field=models.IntegerField(default=1, verbose_name='Intelligence'),
        ),
        migrations.AlterField(
            model_name='player',
            name='strength',
            field=models.IntegerField(default=1, verbose_name='Strength'),
        ),
    ]
