# Generated by Django 3.0.7 on 2020-06-28 13:30

import autoslug.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_0', models.CharField(max_length=80)),
                ('name_0', models.CharField(max_length=80)),
                ('gid_1', models.CharField(max_length=80)),
                ('name_1', models.CharField(max_length=80)),
                ('nl_name_1', models.CharField(blank=True, max_length=80, null=True)),
                ('gid_2', models.CharField(max_length=80)),
                ('name_2', models.CharField(max_length=80)),
                ('varname_2', models.CharField(blank=True, max_length=80, null=True)),
                ('nl_name_2', models.CharField(blank=True, max_length=80, null=True)),
                ('type_2', models.CharField(max_length=80)),
                ('engtype_2', models.CharField(blank=True, max_length=80, null=True)),
                ('cc_2', models.CharField(blank=True, max_length=80, null=True)),
                ('hasc_2', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name_2')),
            ],
            options={
                'ordering': ['name_2'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('abbreviation', models.CharField(max_length=4)),
                ('is_canonical', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorldBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('pop2005', models.IntegerField(verbose_name='Population 2005')),
                ('fips', models.CharField(max_length=2, verbose_name='FIPS Code')),
                ('iso2', models.CharField(max_length=2, verbose_name='2 Digit ISO')),
                ('iso3', models.CharField(max_length=3, verbose_name='3 Digit ISO')),
                ('un', models.IntegerField(verbose_name='United Nations Code')),
                ('region', models.IntegerField(verbose_name='Region Code')),
                ('subregion', models.IntegerField(verbose_name='Sub-Region Code')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
            ],
        ),
        migrations.CreateModel(
            name='TravelDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_distance_value', models.DecimalField(decimal_places=12, default=0, max_digits=18)),
                ('_distance_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='world.Unit')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.CountryDivision')),
            ],
        ),
        migrations.AddField(
            model_name='countrydivision',
            name='distances',
            field=models.ManyToManyField(related_name='_origin', to='world.TravelDetails'),
        ),
        migrations.AddField(
            model_name='countrydivision',
            name='world_border',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='world.WorldBorder'),
        ),
    ]
