# Generated by Django 3.0.4 on 2020-03-14 19:21

import autoslug.fields
from django.db import migrations
import django.utils.text


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldborder',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='djangodbmodelsfieldscharfield', editable=False, populate_from='name', slugify=django.utils.text.slugify),
        ),
    ]
