# Generated by Django 3.0.4 on 2020-03-15 14:24

import autoslug.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_worldborder_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_0', models.CharField(max_length=80)),
                ('name_0', models.CharField(max_length=80)),
                ('gid_1', models.CharField(max_length=80)),
                ('name_1', models.CharField(max_length=80)),
                ('nl_name_1', models.CharField(max_length=80)),
                ('gid_2', models.CharField(max_length=80)),
                ('name_2', models.CharField(max_length=80)),
                ('varname_2', models.CharField(max_length=80)),
                ('nl_name_2', models.CharField(max_length=80)),
                ('type_2', models.CharField(max_length=80)),
                ('engtype_2', models.CharField(max_length=80)),
                ('cc_2', models.CharField(max_length=80)),
                ('hasc_2', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
    ]
