# Generated by Django 3.0.4 on 2020-03-15 14:53

from django.db import migrations, models
import django.db.models.deletion


def migrate_countrydivision(apps, schema_editor):
    """Find the relevant world border instance, and apply this to our models"""

    WorldBorder = apps.get_model("world", "WorldBorder")
    CountryDivision = apps.get_model("world", "CountryDivision")
    country_divisions = CountryDivision.objects.all()
    for country_division in country_divisions:
        country_division.world_border = WorldBorder.objects.get(iso3=country_division.gid_0)
        country_division.save()


def reverse_migrate_model_y(apps, schema_editor):
    """This is necessary to reverse migrations later, if we need to"""
    CountryDivision = apps.get_model("world", "CountryDivision")
    country_divisions = CountryDivision.objects.all()
    for country_division in country_divisions:
        country_division.world_border = None
        country_division.save()


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0007_auto_20200315_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydivision',
            name='world_border',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='world.WorldBorder'),
        ),
        migrations.RunPython(migrate_countrydivision, reverse_code=reverse_migrate_model_y)
    ]
