# Generated by Django 3.0.4 on 2020-03-15 15:42

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0008_countrydivision_world_border'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydivision',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name_2'),
            preserve_default=False,
        ),
    ]
