# Generated by Django 3.0.4 on 2020-03-29 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0009_countrydivision_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('abbreviation', models.CharField(max_length=4)),
                ('is_canonical', models.BooleanField(default=False)),
            ],
        ),
    ]
