# Generated by Django 3.0.4 on 2020-03-29 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_auto_20200329_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_distance_value', models.DecimalField(decimal_places=12, default=0, max_digits=18)),
                ('_distance_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='world.Unit')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.CountryDivision')),
            ],
        ),
    ]
