# Generated by Django 3.0.4 on 2020-03-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0013_auto_20200329_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydivision',
            name='distances',
            field=models.ManyToManyField(related_name='origin', to='world.TravelDetails'),
        ),
    ]
