# Generated by Django 3.0.4 on 2020-03-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0015_auto_20200329_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydivision',
            name='distances',
            field=models.ManyToManyField(related_name='_origin', to='world.TravelDetails'),
        ),
    ]
